import { container } from "tsyringe";
import { Database } from "./client";
import { initLevelRange } from "./entity/SALARY/level_range";
import { initLevel } from "./entity/SALARY/level";
import { initAccessSetting } from "./entity/SALARY/access_setting";
import { initAttendanceSetting } from "./entity/SALARY/attendance_setting";
import { initBankSetting } from "./entity/SALARY/bank_setting";
import { initBasicInfo } from "./entity/SALARY/basic_info";
import { initBonusWorkType } from "./entity/SALARY/bonus_work_type";
import { initBonusDepartment } from "./entity/SALARY/bonus_department";
// import { initBonusPositionType } from "./entity/SALARY/bonus_position_type";
import { initBonusPosition } from "./entity/SALARY/bonus_position";
import { initBonusSeniority } from "./entity/SALARY/bonus_seniority";
import { initBonusSetting } from "./entity/SALARY/bonus_setting";
import { initEmployeeAccount } from "./entity/SALARY/employee_account";
import { initEmployeeData } from "./entity/SALARY/employee_data";
import { initEmployeePayment } from "./entity/SALARY/employee_payment";
import { initEmployeeTrust } from "./entity/SALARY/employee_trust";
import { initHolidaysType } from "./entity/SALARY/holidays_type";
import { initInsuranceRateSetting } from "./entity/SALARY/insurance_rate_setting";
import { initPerformanceLevel } from "./entity/SALARY/performance_level";
import { initTransaction } from "./entity/SALARY/transaction";
import { initTrustMoney } from "./entity/SALARY/trust_money";
import { batchCreateSalaryIncomeTax } from "./entity/SALARY/salary_income_tax";
import { initUser } from "./entity/SALARY/user";
import { initEmployeeBonus } from "./entity/SALARY/employee_bonus";
import { initBonusAll } from "./entity/SALARY/bonus_all";
import { initIncomeTaxSetting } from "./entity/SALARY/income_tax_setting";
import { initNotification } from "./entity/SALARY/notification";
// import { initEmployeeDataMut } from "./entity/SALARY/employee_data_mut";

const sequelize = container.resolve(Database).connection;
console.log("Init Database Tables")

initAccessSetting(sequelize);
initAttendanceSetting(sequelize);
initBankSetting(sequelize);
initBasicInfo(sequelize);
initBonusAll(sequelize);
initBonusWorkType(sequelize);
initBonusDepartment(sequelize);
// initBonusPositionType(sequelize);
initBonusPosition(sequelize);
initBonusSeniority(sequelize);
initBonusSetting(sequelize);
initEmployeeAccount(sequelize);
initEmployeeData(sequelize);
initEmployeePayment(sequelize);
initEmployeeTrust(sequelize);
initEmployeeBonus(sequelize);
initHolidaysType(sequelize);
initInsuranceRateSetting(sequelize);
initLevelRange(sequelize);
initLevel(sequelize);
initPerformanceLevel(sequelize);
batchCreateSalaryIncomeTax(sequelize);
initTransaction(sequelize);
initTrustMoney(sequelize);
initUser(sequelize);
initNotification(sequelize);
// initEmployeeDataMut(sequelize);

initIncomeTaxSetting(sequelize);
